### ISSUE TITLE
['cups']['printers'] attribute structure

### ISSUE THREAD

**Issue by chuhn** [biola/chef-cups#5]
['cups']['printers'] is an array of hashes, one hash per printer.
What's the reason for that?
Order shouldn't matter here, so it could simply be a single hash ie.;
```
{ 'printer1' => { ... }, 'printer2' => { ... }, ... }
```
instead of
```
[ { 'printer1' => { ... } }, { 'printer2' => { ... } }, ... ]
```

Cheers,
   Christopher

**Comment by troyready** [comment]
Yeah, that's a good idea. If you wanted to put together a PR to make the transition, we could definitely pull that in and move the cookbook to v1 (or perhaps include backwards compatibility to leave it < v1).

Otherwise, I'll look at implementing this at some point.
